### ISSUE TITLE
IPFS Chunking Spec Diagrams

### ISSUE THREAD

**Issue by Shrinks99** [webrecorder/specs#138]
### Todo 

- [x] WARC chunking & DAG diagram
- [x] WACZ zip file-stream diagram
- [x] WARC chunk types diagram
- [x] WARC response record illustrated

Mauve's Diagram:
<img width="816" alt="Screenshot 2023-03-08 at 9 47 18 PM" src="https://user-images.githubusercontent.com/5672810/223903123-373facc7-53be-474c-b002-fdeb013e119a.png">

<img width="832" alt="Screenshot 2023-03-09 at 2 46 41 PM" src="https://user-images.githubusercontent.com/5672810/224137404-693b6fe3-359b-4b5b-bd19-cb116d155935.png">

**Comment by Shrinks99** [comment]
These are done now!  I'm not makin more of em!

...Unless I need to and then I will!
